### ISSUE TITLE
Issues when adding custom methods to Array.Prototype with bigdecimal.js

### ISSUE THREAD

**Issue by benmccormick** [iriscouch/bigdecimal.js#9] opened 2012-12-06 03:58 UTC
I'm seeing any issues when I add custom functions to Array.prototype while using the BigDecimal.js library.

Specifically it fails with a traceback to line 295:

function mb(b){return function(){try{return nb(b,this,arguments)}catch(a){throw a}}}

with this exception:
Uncaught java.lang.RuntimeException: Unknown call signature for obj = new java.math.BigDecimal: string function 

I've tried multiple function names and it doesn't appear to be a naming collision, it just seems to be checking the methods on Array.prototype and failing for some reason if there are nonstandard methods.

**Comment by thatguy** [comment] 2012-12-29 15:56
I am having the same issue when I try to use BigDecimal. Here is a short example that illustrates the issue. Tested using BigDecimal v0.6.1, in Google Chrome v23.0.1271.101.

``` html
<!DOCTYPE html>
<html>
  <head>
    <script src="bigdecimal.js" type="text/javascript"></script>

    <script type='text/javascript'>
      function start() {
        var output = document.getElementById("output");

        // Create a BigDecimal object successfully
        var x = new BigDecimal(0.5);
        output.innerHTML += x.toString();

        // Define a method on Array prototype
        Array.prototype.sum = function() {};

        // Try to create another BigDecimal.
        // This time it results in: 
        // "Uncaught java.lang.RuntimeException: Unknown call signature for obj = new java.math.BigDecimal: number function"
        var y = new BigDecimal(0.5);
        output.innerHTML += y.toString();
      }
    </script>
  </head>

  <body onload='javascript:start();'>
    <div id='output'></div>  
  </body>

</html>
```

**Comment by thatguy** [comment] 2012-12-30 01:37
Using a javascript console I was able to narrow the issue down. The function jsArgs.signature attempts to loop through all items in an array and check their type. But the code is using enumeration which causes the loop to look at all properties on the object instead of only looking at the contents of the array.

```
> a = new Array(1,2,'c');
[1, 2, "c"]
> for(x in a) { console.log(x, a[x], typeof(a[x])); }
0 1 number
1 2 number
2 c string


> Array.prototype.sum = function() { };
function () { }
> for(x in a) { console.log(x, a[x], typeof(a[x])); }
0 1 number
1 2 number
2 c string
sum function () { } function
```

So the problem is that it intends to loop through the contents of the array, but is actually looping through all properties on the object.

"for-in should be avoided, that statement is meant to enumerate object properties."
(Source: http://stackoverflow.com/questions/3010840/loop-through-array-in-javascript)

Changing jsArgs.signature to use a standard for loop appears to fix the problem:

``` javascript
public static final native String signature(JsArgs self) /*-{
  var result = [];
  for (var i = 0; i < self.length; i++) {
    var type = typeof(self[i]);
    if(type != 'object')
      result[result.length] = type;
    else if(self[i] instanceof Array)
      result[result.length] = 'array';
    else {
      // An object, but possibly an instance of a known type.
      if($wnd && $wnd.bigdecimal && $wnd.bigdecimal.BigInteger && (self[i] instanceof $wnd.bigdecimal.BigInteger))
        result[result.length] = 'BigInteger';
      else if($wnd && $wnd.bigdecimal && $wnd.bigdecimal.BigDecimal && (self[i] instanceof $wnd.bigdecimal.BigDecimal))
        result[result.length] = 'BigDecimal';
      else if($wnd && $wnd.bigdecimal && $wnd.bigdecimal.RoundingMode && (self[i] instanceof $wnd.bigdecimal.RoundingMode))
        result[result.length] = 'RoundingMode';
      else if($wnd && $wnd.bigdecimal && $wnd.bigdecimal.MathContext && (self[i] instanceof $wnd.bigdecimal.MathContext))
        result[result.length] = 'MathContext';
      else
        result[result.length] = 'object';
    }
  }
  return result.join(' ');
}-*/;
```

Or as seen in the minified version:

``` javascript
function Lj(a){var b=[];for(var i=0;i<a.length;i++){var d=typeof a[i];d!=ws?(b[b.length]=d):a[i] instanceof Array?(b[b.length]=js):$wnd&&$wnd.bigdecimal&&$wnd.bigdecimal.BigInteger&&a[i] instanceof $wnd.bigdecimal.BigInteger?(b[b.length]=is):$wnd&&$wnd.bigdecimal&&$wnd.bigdecimal.BigDecimal&&a[i] instanceof $wnd.bigdecimal.BigDecimal?(b[b.length]=ps):$wnd&&$wnd.bigdecimal&&$wnd.bigdecimal.RoundingMode&&a[i] instanceof $wnd.bigdecimal.RoundingMode?(b[b.length]=xs):$wnd&&$wnd.bigdecimal&&$wnd.bigdecimal.MathContext&&a[i] instanceof $wnd.bigdecimal.MathContext?(b[b.length]=os):(b[b.length]=ws)}return b.join(ys)}
```

**Comment by jhs** [comment] 2012-12-30 03:59
Yes, that was my own poor discipline. Merged your pull request. Thanks!

**Closed as completed by jhs** 2012-12-30 03:59 UTC

**Comment by thatguy** [comment] 2012-12-30 14:38
I feel like my comments on the issue, and pull request were a little to-the-point. I should also say thanks for all of your great work on this!

Thanks!

**Comment by jhs** [comment] 2012-12-31 08:46
You're welcome! No offense taken. I always wish I could say thanks in the pull requests without either (a) polluting the commit history or (b) creating two email events.
